### ISSUE TITLE
lots of warnings

### ISSUE THREAD

**Issue by cburgard** [biojppm/c4core#1]
I'm attempting to include rapidyml as a submodule in a (much) larger project. However, I get lots of warnings, probably from propagation of compiler flags from the higher-level CMakeLists.txt

It would be nice if these could be fixed, or at least disabled explicitly (with "-Wno...") in the CMakeLists.txt!
[warnings.txt](https://github.com/biojppm/c4core/files/3807622/warnings.txt)

This is using g++ 9.1.0 on archlinux.

**Comment by biojppm** [comment]
Thanks for the report and the file with the errors, @cburgard ! I'm going to setup tests with -Wall -Werror -Wpedantic in the hope of catching these and other possible warnings in my code.

**Comment by biojppm** [comment]
There were indeed lots of required fixes. They were hidden by a regression in the cmake code, which no longer enabled pedantic errors when running the unit tests in CI. These errors are now enabled by default as they were always supposed to. So from now on, no errors should pop up.

I'm also going to improve the CI to run the later gcc9 and clang10 versions, which have more stringent warnings. Currently the CI goes only up to gcc7 / clang6 as far as I recall.

Thanks again for the heads up.
