### ISSUE TITLE
Broken macro definition in fix #94: detection of __ARM_ARCH_8A__ 

### ISSUE THREAD

**Issue by hikinggrass** [biojppm/c4core#122]
Hi,

the fix mentioned in #94 ( https://github.com/biojppm/c4core/commit/af165bc72df7b9f897b8cf68b298dac24db50516 ) unfortunately has a typo so the macro definition is actually broken.

#121 fixes this by repairing the macro

**Comment by biojppm** [comment]
Thanks for reporting! Fixed in #121
