### ISSUE TITLE
Typo - C_4MSVC_VERSION_2019  

### ISSUE THREAD

**Issue by yrHeTaTeJlb** [biojppm/c4core#124]
ryml_all.hpp failed to compile with VS2019 due to follwing error caused by the [typo](https://github.com/biojppm/c4core/blame/8f060a4693eef378e92ac0dff35875bc81b910db/src/c4/compiler.hpp#L39)
```
error C4668: 'C_4MSVC_VERSION_2019' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```

**Comment by biojppm** [comment]
Thanks for reporting!
