### ISSUE TITLE
'Exception': identifier not found

### ISSUE THREAD

**Issue by yrHeTaTeJlb** [biojppm/c4core#126]
Can't compile rapidyaml with exceptions enabled because [Exception](https://github.com/biojppm/c4core/blob/8f060a4693eef378e92ac0dff35875bc81b910db/src/c4/error.cpp#L117C15-L117C24) class is missed

**Comment by biojppm** [comment]
I have trouble understanding this issue. I'm assuming you're using the single header, as this is not a problem in the normal multi-file build. 
The exception header is included in the single header; eg see [the header from 0.1.11](https://github.com/biojppm/c4core/releases/tag/v0.1.11):
![image](https://github.com/biojppm/c4core/assets/325344/00b39747-0d7e-42b9-b915-967e98a19103)

Further, this single header is fully tested in ryml's CI; for example: https://github.com/biojppm/rapidyaml/actions/runs/8747816374/job/24006864212 tests (and all its sibling workflows test) the single header in a variety of scenarios, all including exceptions.

**Comment by yrHeTaTeJlb** [comment]
I don't remember the exact context when I caught this. I assume that there's no Exception class in c++. It should be std::runtime_error most likely

**Comment by biojppm** [comment]
Ah yes, I misread. That was from an older project; I guess that's why the capitalization didn't catch my eye.

**Comment by biojppm** [comment]
And the exception scenario was indeed not tested for this define.
