### ISSUE TITLE
aalloc_impl is not implemented for Android

### ISSUE THREAD

**Issue by yrHeTaTeJlb** [biojppm/c4core#127]
https://github.com/biojppm/c4core/blob/8f060a4693eef378e92ac0dff35875bc81b910db/src/c4/memory_resource.cpp#L76

Maybe posix_memalign is availabe for android? Or for C++17 users std::aligned_alloc can work out?

**Comment by biojppm** [comment]
Maybe, I'm not sure. PR welcome. Whatever it is, it should support C++11 though.

**Comment by biojppm** [comment]
@yrHeTaTeJlb I guess this can be closed?
