### ISSUE TITLE
arm64 Windows support

### ISSUE THREAD

**Issue by sonata22** [biojppm/c4core#134]
Hello! I've recently faced the problem trying to build our code for Windows arm64 which has c4core dependency.
The log I've got:

```
warning: Embedding `vcpkg-configuration` in a manifest file is an EXPERIMENTAL feature.
c4core is only supported on '!uwp & !(windows & arm)', which does not match arm64-windows. This usually means that there are known build failures, or runtime problems, when building other platforms. To ignore this and attempt to build c4core anyway, rerun vcpkg with `--allow-unsupported`.
```

Since I [see here](https://github.com/microsoft/vcpkg/blob/master/ports/c4core/vcpkg.json) that there is no official support for the case yet, I have two questions:
1. Are you planning on supporting arm64-windows in the future?
2. And is there any other way or workaround for building for arm64 on Windows?

**Comment by biojppm** [comment]
The vcpkg recipe is provided downstream of this repo; you should contact the maintainers of the package to address any problems with the recipe.

However, c4core does run on arm64, and you definitely can use c4core without using vcpkg. You have many choices for this; see [the relevant documentation page from rapidyaml](https://rapidyaml.readthedocs.io/latest/sphinx_using.html) and adapt accordingly for c4core.

**Comment by sonata22** [comment]
Thanks for the reply.
