### ISSUE TITLE
Static Assertion Failing at charconv.cpp:144 on VS2019

### ISSUE THREAD

**Issue by trprice** [biojppm/c4core#19]
Good Afternoon,

I updated to the latest rapidyaml repo which has c4core at commit 0a1d7a1. Compiling with VS 2019 I'm seeing the static assertion fail in inline constexpr std::chars_format to_std_fmt(RealFormat_e f).

![image](https://user-images.githubusercontent.com/2263277/95266069-4caa4880-07e7-11eb-8973-19dc37b3fa22.png)

![image](https://user-images.githubusercontent.com/2263277/95266093-592ea100-07e7-11eb-8094-17865c985fec.png)

**Comment by trprice** [comment]
Dupe

**Comment by biojppm** [comment]
Fixed in #16
