### ISSUE TITLE
Static Assertion Failure 

### ISSUE THREAD

**Issue by trprice** [biojppm/c4core#20]
Good Afternoon,

I updated to the latest rapidyaml repo which has c4core at commit 0a1d7a1. Compiling with VS 2019 I'm seeing the static assertion fail in inline constexpr std::chars_format to_std_fmt(RealFormat_e f).

![image](https://user-images.githubusercontent.com/2263277/95266069-4caa4880-07e7-11eb-8973-19dc37b3fa22.png)

![image](https://user-images.githubusercontent.com/2263277/95266093-592ea100-07e7-11eb-8094-17865c985fec.png)

**Comment by trprice** [comment]
And please let me know if there is more information that I can provide to help this along. This looks to be regarding the C++17 to_chars().

**Comment by trprice** [comment]
Looks like this is actually an issue on rapidyaml not having an updated version of c4core as a submodule since charconv.hpp has been updated her. I ran the following on my local rapidyaml repo and it now works:

```
git submodule update --remote --merge --recursive
```

**Comment by biojppm** [comment]
Hi @trprice - thanks for the detailed report. Indeed this was fixed in #16; I'm closing this as the problem is now in rapidyaml. I'll do an update of the submodule in rapidyaml.
