### ISSUE TITLE
Add SOVERSION

### ISSUE THREAD

**Issue by musicinmybrain** [biojppm/c4core#35]
Would you consider adding an [SOVERSION](https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html) for those who want to build `c4core` as a shared library?

[Here](https://github.com/AOMediaCodec/libavif/blob/db275902edb11767e3d0ebba483a14e39ccac1fd/CMakeLists.txt#L15) is a good example of how the ABI version number should be formed. [Here](https://github.com/AOMediaCodec/libavif/blob/db275902edb11767e3d0ebba483a14e39ccac1fd/CMakeLists.txt#L411) is where it is applied to the library target.

Adding an `SOVERSION` is a prerequisite for installing `c4core` as a system-wide shared library in a Linux distribution. (I’m looking to package it in Fedora Linux as a dependency for `rapidyaml`.) Shared library versioning [can be added downstream](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_downstream_so_name_versioning), but upstream is much better.

**Comment by biojppm** [comment]
Of course, it should be there.

**Comment by biojppm** [comment]
Fixed in [v0.1.1](https://github.com/biojppm/c4core/releases/tag/v0.1.1)

**Comment by musicinmybrain** [comment]
Thanks!

**Comment by biojppm** [comment]
@musicinmybrain Thanks for packaging for Fedora. When you're ready, could you let me know the package name so that it gets added in [ryml's README](https://github.com/biojppm/rapidyaml/blob/master/README.md)?

**Comment by musicinmybrain** [comment]
> @musicinmybrain Thanks for packaging for Fedora! When you're ready, could you let me know the package name so that it gets added in [ryml's README](https://github.com/biojppm/rapidyaml/blob/master/README.md)?

Sure! It’ll be a little while, between packaging effort and waiting for reviews, but I’ll let you know when I get there.
