### ISSUE TITLE
Release 0.1.5 has version 0.1.4 in the source

### ISSUE THREAD

**Issue by musicinmybrain** [biojppm/c4core#41]
Thanks for your recent work on fixing support for alternative architectures.

As of the tag for release 0.1.5, `CMakeLists.txt` and `tbump.toml` still contain the version number `0.1.4`. Can I assume this was an oversight?

**Comment by biojppm** [comment]
Thanks for reporting. Indeed it was an oversight; I will now have to release 0.1.6 to fix that; let's hope it does go well, as I've had some trouble (much more work than I wanted) to get all the CI and release stuff working as I think it should.

**Comment by biojppm** [comment]
[Release 0.1.6](https://github.com/biojppm/c4core/releases/tag/v0.1.6) is out now. Hoping everything's OK now.
