### ISSUE TITLE
c4/time.cpp doesn't compile on Unix

### ISSUE THREAD

**Issue by mbs-c** [biojppm/c4core#43]
In c4/time.cpp, it is assumed that `CLOCK_MONOTONIC_RAW` is available on all POSIX systems:

https://github.com/biojppm/c4core/blob/9b19498a679ff3e3ee312de6fde5a5c5832e06e2/src/c4/time.cpp#L38-L44

This clock source is Linux-specific, though, which causes builds on e.g. AIX to fail. (See documentation at https://linux.die.net/man/2/clock_gettime.)

**Comment by biojppm** [comment]
@mbs-c did you arrive at a confirmed fix for this in AIX? If so, could you submit a PR?

**Comment by mbs-c** [comment]
Sorry, I totally forgot about this issue. I will submit a PR later today.
