### ISSUE TITLE
Please add RISC-V suppport

### ISSUE THREAD

**Issue by CoelacanthusHex** [biojppm/c4core#66]
I meet problem when I try to compile rapidyaml (it uses c4core) on RISC-V, CMake output
```
CMake Error at ext/c4core/cmake/TargetArchitecture.cmake:28 (message):
  unknown target architecture: unknown
Call Stack (most recent call first):
  api/CMakeLists.txt:22 (c4_get_architecture_defines)
```
I think it is caused by https://github.com/biojppm/cmake/blob/master/TargetArchitecture.cmake no support for risc-v.
Hope you can add support soon.

**Comment by biojppm** [comment]
Thanks for reporting. Happy to accept a  PR for this; the fixed are likely simple, but it is time-costly for me to set up something which is verifiable, both for the CI and cross compilation, and at the moment I can't do that.
