### ISSUE TITLE
Warning about potential deference of null pointer

### ISSUE THREAD

**Issue by linw789** [biojppm/c4core#82]
Hi,

Thank you for making rapidyaml. I'm trying to add it to my project but got this warning: `warning C6011: dereferencing NULL pointer str` at here: https://github.com/biojppm/c4core/blob/master/src/c4/substr.hpp#L228

My compiler: Visual Studio 2022 (Visual C++ 2022   00482-90000-00000-AA937) 

I see that in the next `compare` function below, `if(C4_LIKELY(str && that))` is used. Can we use `C4_LIKELY` in both `compare` functions?

**Comment by biojppm** [comment]
Thanks for reporting. Unfortunately, `C4_LIKELY` has no effect in Visual Studio, and using it here would cause branch misses. Looking at the function:
```c++
    int compare(C const c) const
    {
        C4_XASSERT((str != nullptr) || len == 0);
        if( ! len)
            return -1;
        if(*str == c)
            return static_cast<int>(len - 1);
        return *str - c;
    }
```
Maybe a possible workaround is this (relying on the asserted equivalence between `!len` and `!str`):
```c++
    int compare(C const c) const
    {
        C4_XASSERT((str != nullptr) || len == 0);
        if( ! str)
            return -1;
        else if(*str == c)
            return static_cast<int>(len - 1);
        return *str - c;
    }
```
By the way, c4core's CI is (or should be) testing everything with pedantic warnings cranked to max as errors, including in VS2022, and I don't see this warning. The coverage data [shows this function is covered](https://app.codecov.io/gh/biojppm/c4core/blob/master/src/c4/substr.hpp), and the situation seems strange. I will need to figure what why.

**Comment by biojppm** [comment]
Refactored in b8f2110. Feel free to reopen if the problem persists.
