### ISSUE TITLE
 warning C4643 when compiling with Visual Studio 2022 

### ISSUE THREAD

**Issue by MichaelGoulding** [biojppm/c4core#85]
c4\std\vector_fwd.hpp(11): warning C4643: Forward declaring 'allocator' in namespace std is not permitted by the C++ Standard.
c4\std\vector_fwd.hpp(12): warning C4643: Forward declaring 'vector' in namespace std is not permitted by the C++ Standard.
c4\std\string_fwd.hpp(22): warning C4643: Forward declaring 'char_traits' in namespace std is not permitted by the C++ Standard.
c4\std\string_fwd.hpp(23): warning C4643: Forward declaring 'allocator' in namespace std is not permitted by the C++ Standard.
c4\std\string_fwd.hpp(24): warning C4643: Forward declaring 'basic_string' in namespace std is not permitted by the C++ Standard.

**Comment by biojppm** [comment]
Apologies for the late reply.

Those forward declarations are about a nagging chicken-and-egg situation prompted by wanting `<vector>` et al to be optional in the library. The current situation is not ideal and requires revisiting to ideally never fwd-declare these containers. But to be clear, if in the end a fwd-declare is what it takes, then I will still have it.

Anyway, for now I will suppress these warnings.

**Comment by biojppm** [comment]
@MichaelGoulding I'm closing this now; feel free to reopen if the warning resurfaces.
